// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;
using System.Drawing;
using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace ExamplesChat.iOS
{
	public partial class ChatWindow : UIViewController
	{
        RectangleF originalViewSize = new RectangleF(0,0, 320,416);

		public ChatWindow (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            NSNotificationCenter.DefaultCenter.AddObserver(UIKeyboard.DidHideNotification, HandleKeyboardDidHide);
            NSNotificationCenter.DefaultCenter.AddObserver(UIKeyboard.DidShowNotification, HandleKeyboardDidShow);

            //Remove the keyboard on a tap
            var tap = new UITapGestureRecognizer();
            tap.AddTarget(() =>
            {
                this.View.EndEditing(true);
            });
            this.View.AddGestureRecognizer(tap);
        }

        void HandleKeyboardDidShow(NSNotification notification)
        {
            NSObject value = notification.UserInfo[UIKeyboard.FrameEndUserInfoKey];
            RectangleF keyboardFrame = ((NSValue)value).RectangleFValue;

            ChatView.Frame = new System.Drawing.RectangleF(ChatView.Frame.X, ChatView.Frame.Y, ChatView.Frame.Width, ChatView.Frame.Height - keyboardFrame.Height);
        }

        void HandleKeyboardDidHide(NSNotification notification)
        {
            // scroll back to normal
            ChatView.Frame = originalViewSize;
        }
	}
}
