// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace ExamplesChat.iOS
{
	public partial class Settings : UIViewController
	{
		public Settings (IntPtr handle) : base (handle)
		{
		}
	}
}
