#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ExamplesChat.Android.Resource", IsApplication=true)]

namespace ExamplesChat.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			DPSBase.Resource.Drawable.monoandroidsplash = ExamplesChat.Android.Resource.Drawable.monoandroidsplash;
			DPSBase.Resource.Layout.monoandroidsplash = ExamplesChat.Android.Resource.Layout.monoandroidsplash;
			DPSBase.Resource.String.ApplicationName = ExamplesChat.Android.Resource.String.ApplicationName;
			DPSBase.Resource.String.Hello = ExamplesChat.Android.Resource.String.Hello;
			DPSBase.Resource.Style.Mono_Android_Theme_Splash = ExamplesChat.Android.Resource.Style.Mono_Android_Theme_Splash;
			NetworkCommsDotNet.Resource.Drawable.monoandroidsplash = ExamplesChat.Android.Resource.Drawable.monoandroidsplash;
			NetworkCommsDotNet.Resource.Layout.monoandroidsplash = ExamplesChat.Android.Resource.Layout.monoandroidsplash;
			NetworkCommsDotNet.Resource.String.ApplicationName = ExamplesChat.Android.Resource.String.ApplicationName;
			NetworkCommsDotNet.Resource.String.Hello = ExamplesChat.Android.Resource.String.Hello;
			NetworkCommsDotNet.Resource.Style.Mono_Android_Theme_Splash = ExamplesChat.Android.Resource.Style.Mono_Android_Theme_Splash;
			SevenZipLZMACompressor.Resource.Drawable.monoandroidsplash = ExamplesChat.Android.Resource.Drawable.monoandroidsplash;
			SevenZipLZMACompressor.Resource.Layout.monoandroidsplash = ExamplesChat.Android.Resource.Layout.monoandroidsplash;
			SevenZipLZMACompressor.Resource.String.ApplicationName = ExamplesChat.Android.Resource.String.ApplicationName;
			SevenZipLZMACompressor.Resource.String.Hello = ExamplesChat.Android.Resource.String.Hello;
			SevenZipLZMACompressor.Resource.Style.Mono_Android_Theme_Splash = ExamplesChat.Android.Resource.Style.Mono_Android_Theme_Splash;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int MyButton = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int monoandroidsplash = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
