#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ExamplesChat.Android.Resource", IsApplication=true)]

namespace ExamplesChat.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::NetworkCommsDotNet.Resource.String.ApplicationName = global::ExamplesChat.Android.Resource.String.ApplicationName;
			global::NetworkCommsDotNet.Resource.String.Hello = global::ExamplesChat.Android.Resource.String.Hello;
			global::ProtobufSerializer.Resource.String.ApplicationName = global::ExamplesChat.Android.Resource.String.ApplicationName;
			global::ProtobufSerializer.Resource.String.Hello = global::ExamplesChat.Android.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int ConnectionTypes = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070005
			public const int connectionTypeSpinner = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int enableLocalServer = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int enableServerLabel = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int encryptionLabel = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int ipPortLabel = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int ipTextInput = 2131165185;
			
			// aapt resource value: 0x7f07000a
			public const int mainText = 2131165194;
			
			// aapt resource value: 0x7f070008
			public const int mainTextScroll = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int messageTextInput = 2131165193;
			
			// aapt resource value: 0x7f070002
			public const int portSeperatorLabel = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int portTextInput = 2131165187;
			
			// aapt resource value: 0x7f07000b
			public const int sendButton = 2131165195;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
